version: '3.8'

services:
  app:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/nestjs
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network: